-- Generated by yeet-initdb --print-schema. Do not edit.
-- Schema version 1.

-- migration 1 (initial)
CREATE TABLE job (
  id             INTEGER PRIMARY KEY,
  name           TEXT    NOT NULL UNIQUE,
  command        TEXT    NOT NULL,
  args           TEXT    NOT NULL DEFAULT '[]'
                   CHECK (json_valid(args) AND json_type(args) = 'array'),
  cron           TEXT,
  enabled        INTEGER NOT NULL DEFAULT 1 CHECK (enabled IN (0, 1)),
  timeout_s      INTEGER NOT NULL DEFAULT 300 CHECK (timeout_s > 0),
  cwd            TEXT,
  overlap_policy TEXT    NOT NULL DEFAULT 'skip'
                   CHECK (overlap_policy IN ('skip', 'parallel')),
  created_at     TEXT    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at     TEXT    NOT NULL DEFAULT CURRENT_TIMESTAMP
) STRICT;

CREATE TABLE run (
  id           INTEGER PRIMARY KEY,
  job_id       INTEGER NOT NULL REFERENCES job(id) ON DELETE CASCADE,
  job_name     TEXT    NOT NULL,
  command      TEXT    NOT NULL,
  args         TEXT    NOT NULL,
  source       TEXT    NOT NULL
                 CHECK (source IN ('cron', 'catchup', 'manual')),
  status       TEXT    NOT NULL
                 CHECK (status IN ('running', 'success', 'failure', 'timeout',
                                   'spawn_error', 'orphaned', 'misfire',
                                   'skipped')),
  scheduled_at TEXT    NOT NULL,
  started_at   TEXT    NOT NULL,
  finished_at  TEXT,
  duration_ms  INTEGER,
  pid          INTEGER,
  exit_code    INTEGER,
  term_signal  INTEGER,
  misfire_count INTEGER NOT NULL DEFAULT 0,
  boot_id      TEXT    NOT NULL,
  stdout_text  TEXT,
  stderr_text  TEXT,
  stdout_bytes INTEGER NOT NULL DEFAULT 0,
  stderr_bytes INTEGER NOT NULL DEFAULT 0,
  truncated    INTEGER NOT NULL DEFAULT 0 CHECK (truncated IN (0, 1)),
  error        TEXT
) STRICT;

CREATE TABLE job_state (
  job_id               INTEGER PRIMARY KEY
                         REFERENCES job(id) ON DELETE CASCADE,
  next_fire_at         TEXT,
  last_fire_at         TEXT,
  running_run_id       INTEGER REFERENCES run(id) ON DELETE SET NULL,
  consecutive_failures INTEGER NOT NULL DEFAULT 0,
  last_error           TEXT,
  updated_at           TEXT    NOT NULL DEFAULT CURRENT_TIMESTAMP
) STRICT;

CREATE UNIQUE INDEX run_cron_slot ON run (job_id, scheduled_at)
  WHERE source IN ('cron', 'catchup');

CREATE INDEX run_job_started ON run (job_id, started_at DESC);

CREATE INDEX run_open ON run (status) WHERE status = 'running';

CREATE INDEX job_state_due ON job_state (next_fire_at)
  WHERE next_fire_at IS NOT NULL;

CREATE TRIGGER job_ai_state AFTER INSERT ON job BEGIN
  INSERT INTO job_state (job_id) VALUES (NEW.id);
END;

CREATE TRIGGER job_au_reschedule
AFTER UPDATE OF cron, enabled ON job BEGIN
  UPDATE job_state
     SET next_fire_at = NULL, updated_at = CURRENT_TIMESTAMP
   WHERE job_id = NEW.id;
END;


PRAGMA user_version = 1;
