open Yeet_lib

let ( let* ) = Result.bind

let usage =
  "Usage: yeet-initdb [-d|--db PATH]\n\n\
  \  Create the yeet database if needed and apply pending migrations.\n\
  \  Safe to re-run; also the upgrade command.\n\n\
   Options:\n\
  \  -d, --db PATH     database path [env YEET_DB, default data/yeet.db]\n\
  \      --print-schema  write the schema SQL to stdout and exit\n\
  \  -h, --help        show this message"

let initdb path =
  Db.with_db Db.open_or_create path (fun db ->
      let* () = Db.apply_pragmas db in
      let* applied = Migrate.run db in
      let* version = Db.user_version db in
      Printf.printf "%s: schema version %d (%d migration(s) applied)\n" path
        version applied;
      Ok ())

(* The daemon's tests load this dump so the schema has exactly one author.
   Regenerate db/schema.sql whenever a migration is added. *)
let print_schema () =
  Printf.printf "-- Generated by yeet-initdb --print-schema. Do not edit.\n";
  Printf.printf "-- Schema version %d.\n" Schema.expected_version;
  List.iter
    (fun (version, name, sql) ->
      Printf.printf "\n-- migration %d (%s)%s\n" version name sql)
    Schema.migrations;
  Printf.printf "\nPRAGMA user_version = %d;\n" Schema.expected_version;
  Ok ()

let () =
  Cli.main ~usage (fun args ->
      let opts = Cli.parse ~boolean:[ [ "--print-schema" ] ] args in
      ignore (Cli.expect_positionals opts 0 "none");
      if Cli.has opts "--print-schema" then print_schema ()
      else initdb (Cli.db_path opts))
